#!/bin/bash

# Source tutorial run functions
source $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

if [ ! -f log.decomposePar ]; then
    ./Allrun.pre
fi

# Run
# runApplication $application
runParallel $application

# Reconstruct case
runApplication reconstructPar -newTimes -latestTime

touch $(basename $PWD).foam

# Surfaces visualization
python3 convert_vtk.py
python3 generate_pvd.py
python3 plot_jet.py

#------------------------------------------------------------------------------
